name: sos
description: "Document everything. Stay safe out there."
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Flutter (Google)
  camera: ^0.11.1
  go_router: ^14.8.1
  intl: ^0.19.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1

  # Community
  efui_bios:
    path: ../efui_bios
  empathetech_flutter_ui: 
    path: ../empathetech_flutter_ui
  permission_handler: ^11.4.0
  feedback: ^3.1.0
  flutter_contacts: ^1.1.9+2
  flutter_localized_locales: ^2.0.5
  flutter_platform_widgets: ^8.0.0
  gal: ^2.3.1
  geolocator: ^13.0.3
  share_plus: ^10.1.4
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: main

dev_dependencies:
  dependency_validator: ^5.0.2
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.5
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/fonts/Roboto-Black.ttf
    - assets/fonts/Roboto-BlackItalic.ttf
    - assets/fonts/Roboto-Bold.ttf
    - assets/fonts/Roboto-BoldItalic.ttf
    - assets/fonts/Roboto-Italic.ttf
    - assets/fonts/Roboto-Light.ttf
    - assets/fonts/Roboto-LightItalic.ttf
    - assets/fonts/Roboto-Medium.ttf
    - assets/fonts/Roboto-MediumItalic.ttf
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Thin.ttf
    - assets/fonts/Roboto-ThinItalic.ttf
    - assets/images/
    - assets/images/logo.png

flutter_launcher_icons:
  image_path: assets/images/logo.png
  adaptive_icon_foreground: assets/images/logo.png
  adaptive_icon_background: "#A520DA"
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter_native_splash:
  image: assets/images/logo.png
  color: "#A520DA"
  android: true
  ios: true
  web: false